Fix building dhcpcd-qt by default if some binaries are not available.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -417,7 +417,6 @@ if [ -z "$WITH_QT" -o "$WITH_QT" != no ]; then
 		fi
 	fi
 	if [ -x "$QMAKE" ]; then
-		UI="$UI${UI+ }dhcpcd-qt"
 		DHCPCD_QT=true
 		echo "$QMAKE"
 	else
@@ -425,6 +424,18 @@ if [ -z "$WITH_QT" -o "$WITH_QT" != no ]; then
 		if [ -n "$WITH_QT" ]; then
 			echo "No suitable Qt library has been found" >&2
 			exit 1
+		fi
+	fi
+	if $DHCPCD_QT; then
+		QMAKE_CONFIG="$QMAKE_CONFIG PREFIX=$PREFIX"
+		QMAKE_CONFIG="$QMAKE_CONFIG SYSCONFDIR=$SYSCONFDIR"
+		QMAKE_CONFIG="$QMAKE_CONFIG MANDIR=$MANDIR"
+		if (cd src/dhcpcd-qt; $QMAKE $QMAKE_CONFIG dhcpcd-qt.pro); then
+			UI="$UI${UI+ }dhcpcd-qt"
+		else
+			echo "Failed to configure dhcpcd-qt" >&2
+			[ -n "$WITH_QT" ] && exit 1
+			DHCPCD_QT=false
 		fi
 	fi
 fi
@@ -505,11 +516,3 @@ echo
 
 echo "MKDIR=		\${TOPDIR}/mk" >>$CONFIG_MK
 
-if $DHCPCD_QT; then
-	QMAKE_CONFIG="$QMAKE_CONFIG PREFIX=$PREFIX SYSCONFDIR=$SYSCONFDIR"
-	QMAKE_CONFIG="$QMAKE_CONFIG MANDIR=$MANDIR"
-	if ! (cd src/dhcpcd-qt; $QMAKE $QMAKE_CONFIG dhcpcd-qt.pro); then
-		echo "$0: failed to configure dhcpcd-qt" >&2
-		exit 1
-	fi
-fi
