Add KDE notification support.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -352,6 +352,8 @@ echo "LIB_DHCPCD=	$x" >>$CONFIG_MK
 # what we actually need.
 echo "LDADD+=		-Wl,--as-needed" >>$CONFIG_MK
 
+_NOTIFY="$NOTIFY"
+_WITH_GTK="$WITH_GTK"
 if [ "$WITH_GTK" = yes -o -z "$WITH_GTK" ]; then
 	if pkg-config --cflags gtk+-2.0 >/dev/null 2>&3; then
 		WITH_GTK="gtk+-2.0"
@@ -370,8 +372,7 @@ if [ -n "$WITH_GTK" -a "$WITH_GTK" != no ]; then
 	if [ "$NOTIFY" = yes -o -z "$NOTIFY" ]; then
 		if ! pkg-config --cflags libnotify >/dev/null 2>&3; then
 			echo "libnotify not found" >&2
-			[ "$NOTIFY" = yes ] && exit 1
-			NOTIFY=no
+			[ "$NOTIFY" = yes -n "$_WITH_GTK" ] && exit 1
 		fi
 		NOTIFY=yes
 	fi
@@ -403,6 +404,17 @@ elif [ -n "$WITH_QT" -a "$WITH_QT" != no ]; then
 		DHCPCD_QT=true
 	else
 		echo "$0: no suitable QT library has been found" >&2
+		exit 1
+	fi
+fi
+
+NOTIFY="$_NOTIFY"
+if $DHCPCD_QT && [ -z "$NOTFY" -o "$NOTIFY" = yes ]; then
+	if type knotify4 >/dev/null 2>&3; then
+		QMAKE_CONFIG="$QMAKE_CONFIG CONFIG+=has_libkdeui"
+		echo "Building dhcpcd-qt with notification support"
+	elif [ "$NOTIFY" = yes ]; then
+		echo "$0: knotify4 not found" >&2
 		exit 1
 	fi
 fi
